ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;
ALTER TABLE students ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;
ALTER TABLE parents ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ;
